# Generated by Django 5.0.4 on 2024-04-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(help_text="Student's address.", max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(help_text="Student's date of birth."),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(help_text="Student's department.", max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(help_text="Student's email address.", max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text="Student's first name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(help_text="Student's last name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(help_text="Student's mobile number.", max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(help_text="Student's nationality.", max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], help_text="Student's academic year."),
        ),
    ]
