# Generated by Django 5.0.4 on 2024-04-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0002_alter_student_address_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
